version: '3.8'
services:
  db_integrity:
    image: mongo:latest
    container_name: mongodb-integrity-scan
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mariana
      MONGO_INITDB_ROOT_PASSWORD: '111'
    volumes:
      - integrity_scan_data:/data/db
    networks:
      - integrity_network

networks:
  integrity_network:
    driver: bridge

volumes:
  integrity_scan_data: